### PR TITLE
Linux packaging

### PR DESCRIPTION
**Pull request by Majora320**
Some tweaks to the Linux release that make it more digestible for most users/packagers, with the addition of a desktop file. Also removes some of the love-specific files that were generated by the build but that we don't really need in a release package. (Might want to remove those for the Windows/Mac builds too, but I don't use either of those platforms and can't really test anything on them.)

N.B. I'm not sure what `$LOVEBINARYDIRECTORY` is used for, it doesn't seem to be set anywhere and at the end we just zip up `love/*` anyways; might just be empty/removable/a holdover from a previous iteration (unless I'm missing something here).

### CODE REVIEW

**Comment by 0x0ade** [comment]
An initial check on this PR errored due to an Azure Pipelines issue outside of my control. It that has since been resolved - rerunning the failed job passed fine.

`$LOVEBINARYDIRECTORY` is set via `loveBinaryDirectory: ''` in the platform matrix at the top of the file. It exists for all platforms in part for consistency, in part if the main part of Love2D ever gets nested in the archive (which is already the case with macOS due to how it's bundled as an app). That part of `azure-pipelines.yml` can probably be simplified, but I don't see a huge need to do so though.

`src/data/icon.png` already contains a copy of the icon. If you need higher / lower resolution versions or a svg, please let me know and I'll supply such versions. The "original" version of the icon without rounded corners and with padding is 1536 x 1536 pixels large and can be turned into a vector graphic if really necessary. I deemed that a bit overkill even with where display pixel density is headed towards nowadays.

Regarding the icon and especially the desktop file, please check the following: https://github.com/EverestAPI/Olympus/blob/d57ea822513645255bd72afaab24eec11945fc81/src/modinstaller.lua#L42-L87

Admittedly, `modinstaller.lua` isn't an obvious place to contain code that  
- writes the icon to disk,
- drops a desktop file in the user applications folder and
- registers a custom scheme handler.

And now that I'm looking at it again, it might be in need of an optional `XDG_DATA_HOME` check - I'll implement that separately from this PR.

From what I understand, it might be ideal to disable the creation of the user local desktop folder in cases where Olympus will be installed via a package manager. Is there a recommended way to detect that? I'd rather not rely on install path heuristics.

In addition to that, please make sure that your desktop file works with the `everest:` schema (currently most prominently used on [GameBanana](https://gamebanana.com/games/6460), exposed via the "one-click install button" for mods). Also, should Olympus continue registering itself as a schema handler, or should that be handled by the package (/ package manager)?

Other than that, this looks good to me 😃 please keep me up to date on further packaging developments as I'm very interested!

**Comment by Majora320** [comment]
Thanks for the info!

W.R.T. the modinstaller debacle:

On Linux specifically I think it _probably_ doesn't make sense to do that kind of thing in-application, at all; I would lean towards either providing a separate shell script to install everything or providing the files in question and leaving it up to the user/packager. As far as I know there's would be a cross-platform (=cross-packager) way to check if we're installed via a package manager or not. Registering and all that should probably be handled by the packager.

I'd be up to building/maintaining something like that if that seems like a good idea, and an apt package/ppa for Ubuntu-based distributions + an aur package for Arch-based distributions, which seems like a decent way of doing things.

**Comment by 0x0ade** [comment]
Thank you for the reply :) I'll try to follow your advice and separate that setup from modinstaller into a separate bash script after merging your PR... unless you want to do that, given how my experience for Linux has become very lacking after having stopped daily-driving it a few years ago 😅 I'd be very thankful for that.

Hopefully the last few questions before I merge this PR:

- Is `%u` not needed for `Exec` in your desktop file? I added it to mine under the assumption that it'd be necessary for arguments to get passed through when using the `everest` schema.
- Given that your desktop file contains `Exec=olympus` and `Icon=olympus`, what exactly should the install script do? My first instinct would be to copy the entirety of Olympus into `/opt/olympus/` and create symlinks for the bin and icon in... well, where exactly? `/usr/bin/` and `/usr/share/icons/hicolor/128x128/apps/`? (Outside of the scope of this PR: maybe the install script should in fact download the latest stable build and "install" that?)  
Right now the "installation" instructions for Olympus are "unzip the latest stable wherever you want and run olympus.sh". This seems to work fine enough across enough distros given the user feedback I've gotten.

I hope you understand that I'm trying to understand what's going on as I don't want a repeat of this specific Everest PR: https://github.com/EverestAPI/Everest/pull/59

**Comment by Majora320** [comment]
I should have included %u, my apologies; I don't work with desktop files much and when I was looking for docs to write the first one ...the site hosting the .desktop spec was down, so...

For an install script, that sounds like the gist of it. And of course dependency hell is something one would want to avoid :) Some distributions might want to exclude certain packages that you vendor here in favor of the package manager versions (e.g. love or lsqlite), but they can probably just delete things themselves after the install script runs. I can write up a draft PR sometime in the near future if there's interest.

An install script that automatically downloaded the latest stable would be interesting, but I would be wary of too much fragmentation if we're also shipping packages - it can be a pain to maintain multiple separate unrelated ways of installing the same thing.

**Comment by 0x0ade** [comment]
Everything is fine :) there's no need to apologize this politely. Thank you for fixing this before the merge!

Dependency hell is the main reason why [Olympus hotfixes luajit-request by monkeypatching ffi](https://github.com/EverestAPI/Olympus/blob/d57ea822513645255bd72afaab24eec11945fc81/src/prethread.lua#L7-L37) and why the installation instructions previously told users to install Love2D themselves, until some users told me that their distros doesn't even supply that, which then made me ship Love2D with Olympus. ~~Also luarocks making me cry sometimes, but luarocks is a topic for itself.~~

**Comment by Majora320** [comment]
Truly terrifying. It's a wonder that anything works across platforms at all (no doubt due to much blood, sweat, and tears)

**Pull request merged**
